# Generated by Django 4.2.5 on 2024-01-23 07:44
import traceback

import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models


def _populate_opportunity_access(apps, schema_editor):
    try:
        call_command(
            "populate_opportunity_access",
        )
    except Exception:
        traceback.print_exc()


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0028_duplicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="opportunity_access",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityaccess"
            ),
        ),
        migrations.AddField(
            model_name="completedmodule",
            name="opportunity_access",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityaccess"
            ),
        ),
        migrations.AddField(
            model_name="uservisit",
            name="opportunity_access",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="opportunity.opportunityaccess"
            ),
        ),
        migrations.RunPython(_populate_opportunity_access, migrations.RunPython.noop),
    ]
